-- ============================================================================
-- Migration: 0022_seed_knowledge_documents.sql
-- Purpose:   Seed atlas.knowledge_documents with 22 anchor strategy/doctrine
--            documents (Workstream B). Metadata only — no embeddings, no
--            chunks. Status starts as 'proposed' for human-in-loop approval
--            via admin UI before Phase 2b ingestion worker runs.
--
-- Version:   v1.2 — fixes applied per code review 2026-04-27
-- Author:    Drafted by Claude, reviewed by Dayo, executed by Cursor
-- Date:      2026-04-27
--
-- Reversibility: Mostly reversible. Inserts are reversible via DELETE (see
--                rollback block at end). The CHECK constraint update (adding
--                'doctrine') is also reversible via DROP/ADD CONSTRAINT pair.
--
-- v1.1 -> v1.2 fixes:
--   * Bug fix: ORR Technology Adoption published_on corrected from 2024-01-01
--     to 2023-06-01 (TAR published June 2023 per filename; 2024 was a copy
--     error from the adjacent ORR Annual Assessment row).
--   * Bug fix: Innovation Passports storage_key extension .pdf -> .docx
--     (source format is .docx; text-extractor infers format from extension —
--     a .pdf key on a .docx file would cause pdf-parse to fail or produce
--     garbage at ingestion time).
--   * RSSB source_url set to NULL (was a webpage landing page, not a PDF).
--     storage_key already set; ingestion pipeline uses storage_key and
--     source_url is misleading when it points to HTML, not the document.
--   * Rollback DELETE switched from published_on date-matching to title-
--     matching (dates are not unique identifiers; two rows share 2022-07-01).
--   * Future of Freight modes normalised to ['rail','aviation','maritime','hit']
--     (was ['rail','maritime','hit','aviation'] — inconsistent with other
--     cross-cutting docs; array order is cosmetic but consistent is cleaner).
--   * Maritime UK URL annotated as needing verification before ingestion
--     (Annual_Report_17-compressed.pdf filename is anomalous for a 2024 doc).
-- ============================================================================

-- Drizzle's migrator wraps each migration file in its own transaction.
-- BEGIN / COMMIT are intentionally omitted; use --> statement-breakpoint
-- as the Drizzle-standard statement separator throughout this file.

-- ----------------------------------------------------------------------------
-- STEP 1: Extend source_type CHECK constraint to include 'doctrine'
-- ----------------------------------------------------------------------------
-- Existing CHECK list (per migration 0021):
--   white_paper | policy_doc | govt_report | industry_report |
--   guidance_doc | web_article | internal
--
-- We add 'doctrine' for architectural manifesto-type documents
-- (Testbed Britain, Innovation Passports). These are not white papers in the
-- analytical-research sense; they are CPC's normative architectural doctrine.
--
-- Constraint name 'knowledge_documents_source_type_check' confirmed live
-- against pg_constraint on 2026-04-27 (auto-generated by Postgres from the
-- inline CHECK in migration 0021 — no CONSTRAINT NAME clause was used there).

ALTER TABLE atlas.knowledge_documents
  DROP CONSTRAINT IF EXISTS knowledge_documents_source_type_check;
--> statement-breakpoint
ALTER TABLE atlas.knowledge_documents
  ADD CONSTRAINT knowledge_documents_source_type_check
  CHECK (source_type IN (
    'white_paper',
    'policy_doc',
    'govt_report',
    'industry_report',
    'guidance_doc',
    'web_article',
    'internal',
    'doctrine'
  ));
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- STEP 2: Insert 22 anchor documents
-- ----------------------------------------------------------------------------
-- Schema notes (from migration 0021 + Drizzle schema):
--   * modes / themes are text[] — unconstrained at DB level. Drizzle / Zod
--     schemas (KnowledgeModeSchema, KnowledgeThemeSchema) document the
--     allowed string sets in TypeScript. Those schemas need updating in a
--     separate follow-up PR after this seed lands, otherwise agents will
--     filter out the new values (data_digital, infrastructure themes).
--   * status accepts: proposed | approved | retired (no 'ingested')
--   * source_url for direct URL-fetched docs; storage_key for local uploads.
--     When storage_key is set, ingestion pipeline fetches from storage and
--     ignores source_url. source_url is left NULL for local-file documents.
--   * tier: primary | secondary | tertiary
--   * publisher and author are optional text fields
--
-- Local-file documents use storage_key as a placeholder path:
--   'kb/<slug>.ext' — the Phase 2b ingestion worker uploads the actual
--   file to Supabase Storage at this key before triggering ingestion.

-- =========================
-- RAIL (4)
-- =========================

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Network Rail GB CP7 Delivery Plan — Year 2 update',
  'govt_report',
  'https://www.networkrail.co.uk/wp-content/uploads/2025/07/GB-CP7-Delivery-Plan-Year-2-update.pdf',
  NULL,
  'Network Rail',
  '2025-07-01', -- approximate (month known; day set to 01)
  ARRAY['rail']::text[],
  ARRAY['planning_operation','decarbonisation','industry']::text[],
  'primary',
  'Year 2 update of the Control Period 7 (2024-2029) delivery plan. Successor to CP7 SBP. Suggested review cadence: annual.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'RSSB Strategic Business Plan 2024-2029',
  'industry_report',
  NULL, -- local-file doc; original RSSB page is a flipbook (publications.rssb.co.uk);
        -- PDF sourced separately and uploaded to storage_key below.
        -- source_url set to NULL to prevent ingestion pipeline from fetching HTML.
  'kb/rssb-strategic-business-plan-2024-2029.pdf',
  'Rail Safety and Standards Board',
  '2024-02-22',
  ARRAY['rail']::text[],
  ARRAY['planning_operation','people_experience','decarbonisation']::text[],
  'primary',
  'Local-file ingestion. Five-year strategic plan covering safer/healthier/harmonised/efficient/future/sustainable rail.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'ORR Technology Adoption in Network Rail (Targeted Assurance Review)',
  'govt_report',
  'https://www.orr.gov.uk/sites/default/files/2024-01/technology-adoption-in-network-rail-tar-june-2023.pdf',
  NULL,
  'Office of Rail and Road',
  '2023-06-01', -- TAR published June 2023 per filename (2024-01 in URL is ORR's upload date, not publication date)
  ARRAY['rail']::text[],
  ARRAY['autonomy','planning_operation','industry']::text[],
  'primary',
  'ORR Targeted Assurance Review of how Network Rail adopts new technology. Examines technology readiness, adoption pathways, barriers.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'ORR Annual Assessment of Network Rail 2023-2024',
  'govt_report',
  'https://www.orr.gov.uk/sites/default/files/2024-07/annual-assessment-of-network-rail-2023-24.pdf',
  NULL,
  'Office of Rail and Road',
  '2024-07-18',
  ARRAY['rail']::text[],
  ARRAY['planning_operation','people_experience']::text[],
  'secondary',
  'Final year of CP6 assessment (2023-24). Newer 2024-25 assessment now exists at orr.gov.uk/media/27118/download — consider upgrade to primary or replacement once corpus is in production use.',
  'proposed'
);

-- =========================
-- AVIATION (4)
-- =========================

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'UK Jet Zero Strategy: Delivering Net Zero Aviation by 2050',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/62e931d48fa8f5033896888a/jet-zero-strategy.pdf',
  NULL,
  'Department for Transport',
  '2022-07-01', -- approximate
  ARRAY['aviation']::text[],
  ARRAY['decarbonisation','industry']::text[],
  'primary',
  'DfT flagship aviation decarbonisation strategy. Five policy measures: system efficiencies, SAF, zero emission flight, markets and removals, influencing consumers.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Jet Zero Strategy: One Year On',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/64c2463b331a650014934cb0/jet-zero-strategy-one-year-on.pdf',
  NULL,
  'Department for Transport',
  '2023-07-20',
  ARRAY['aviation']::text[],
  ARRAY['decarbonisation','industry']::text[],
  'secondary',
  'Progress update against Jet Zero Strategy. ICAO net zero 2050 agreement, SAF mandate progress, UK ETS aviation expansion.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'ATI Destination Zero: The Technology Journey to 2050',
  'industry_report',
  'https://www.ati.org.uk/wp-content/uploads/2022/04/ATI-Tech-Strategy-2022-Destination-Zero.pdf', -- volatile: ati.org.uk external site; verify URL before ingestion
  NULL,
  'Aerospace Technology Institute',
  '2022-04-01', -- approximate
  ARRAY['aviation']::text[],
  ARRAY['decarbonisation','autonomy','industry']::text[],
  'primary',
  'ATI technology strategy. Sets investment scope for ATI Programme. Three roadmaps: ultra-efficient, zero-carbon, cross-cutting enabling technologies.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'ATI Non-CO2 Technologies Roadmap',
  'industry_report',
  'https://www.ati.org.uk/wp-content/uploads/2024/03/ATI-Non-CO2-Technologies-Roadmap-Report-FINAL-March-2024.pdf', -- volatile: ati.org.uk external site; verify URL before ingestion
  NULL,
  'Aerospace Technology Institute',
  '2024-03-01', -- approximate
  ARRAY['aviation']::text[],
  ARRAY['decarbonisation','industry']::text[],
  'secondary',
  'First-of-kind UK roadmap on non-CO2 aviation emissions (contrails, NOx, water vapour). Informs ATI Non-CO2 Programme launched May 2024.',
  'proposed'
);

-- =========================
-- MARITIME (4)
-- =========================

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'UK Maritime Decarbonisation Strategy',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/67f4dcb3c2fea2548f4eff64/dft-maritime-decarb-strategy-25.pdf',
  NULL,
  'Department for Transport',
  '2025-03-01', -- approximate
  ARRAY['maritime']::text[],
  ARRAY['decarbonisation','industry']::text[],
  'primary',
  'Successor to Clean Maritime Plan 2019. UK targets zero GHG by 2050; 30% by 2030; 80% by 2040. Five key policy measures including UK ETS expansion to maritime from 2026.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Maritime 2050: Navigating the Future',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/872194/Maritime_2050_Report.pdf',
  NULL,
  'Department for Transport',
  '2019-01-01', -- approximate (published January 2019)
  ARRAY['maritime']::text[],
  ARRAY['autonomy','decarbonisation','hubs_clusters','people_experience','industry']::text[],
  'primary',
  'DfT long-horizon maritime strategy. Cross-cutting themes covered. Foundational reference for UK maritime policy direction.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Maritime UK Annual Report 2024',
  'industry_report',
  'https://www.maritimeuk.org/documents/1260/Annual_Report_17-compressed.pdf', -- verify before ingestion: 'Annual_Report_17' filename is anomalous for a 2024 report; confirm URL resolves to correct year's content
  NULL,
  'Maritime UK',
  '2024-10-01', -- approximate
  ARRAY['maritime']::text[],
  ARRAY['industry','people_experience','hubs_clusters']::text[],
  'secondary',
  'Industry body annual report; sector-wide view across UK maritime. Reflects sector priorities, achievements, milestones.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'UK Domestic Maritime Decarbonisation: Plotting the Course to Zero',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/62d7b533d3bf7f285a88f4c4/uk-domestic-maritime-decarbonisation-consultation-plotting-the-course-to-zero.pdf',
  NULL,
  'Department for Transport',
  '2022-07-01', -- approximate
  ARRAY['maritime']::text[],
  ARRAY['decarbonisation']::text[],
  'secondary',
  'Consultation document; precursor evidence base for Maritime Decarbonisation Strategy 2025. Useful for tracing policy development arc.',
  'proposed'
);

-- =========================
-- HIGHWAYS & INTEGRATED TRANSPORT (4)
-- =========================

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Road Investment Strategy 3 (RIS3): 2026-2031',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/69c4265e471d520038d0f64a/ris3.pdf',
  NULL,
  'Department for Transport',
  '2026-03-01', -- approximate
  ARRAY['hit']::text[],
  ARRAY['decarbonisation','people_experience','planning_operation']::text[],
  'primary',
  'National Highways funding settlement for SRN 2026-2031. Over £27 billion of investment, including £24.99 billion to operate, maintain, renew and enhance the network.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Automated Vehicles Act 2024',
  'policy_doc',
  'https://www.legislation.gov.uk/ukpga/2024/10/pdfs/ukpga_20240010_en.pdf',
  NULL,
  'UK Parliament',
  '2024-05-20',
  ARRAY['hit']::text[],
  ARRAY['autonomy']::text[],
  'primary',
  'Primary AV legislation in UK. Introduces self-driving authorisation regime; Authorised Self-Driving Entity (ASDE) and No-User-In-Charge (NUiC) categories; protected marketing terms.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Zenzic UK CAM Roadmap to 2035 — Executive Summary',
  'industry_report',
  'https://zenzic.io/wp-content/uploads/2023/03/Roadmap-to-2035-%E2%80%93Executive-Summary_v6.pdf', -- volatile: zenzic.io external site; verify URL before ingestion
  NULL,
  'Zenzic',
  '2023-03-01', -- approximate
  ARRAY['hit']::text[],
  ARRAY['autonomy','hubs_clusters']::text[],
  'primary',
  'Zenzic CAM (Connected & Automated Mobility) roadmap to 2035. Industry-government coordinated view of UK CAM ecosystem development.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Zenzic UK CAM Roadmap 2035 — Why CAM (Opportunities)',
  'industry_report',
  'https://zenzic.io/wp-content/uploads/2025/06/UK-CAM-Roadmap-2035-Why-CAM-PDF.pdf', -- volatile: zenzic.io external site; verify URL before ingestion
  NULL,
  'Zenzic',
  '2025-06-01', -- approximate
  ARRAY['hit']::text[],
  ARRAY['autonomy','people_experience','decarbonisation']::text[],
  'secondary',
  'Strategic case for CAM update. Companion to executive summary roadmap. Articulates CAM''s contribution to safety, accessibility, decarbonisation, labour challenges.',
  'proposed'
);

-- =========================
-- CROSS-CUTTING TRANSPORT (4)
-- =========================

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'UK Transport Decarbonisation Plan: Decarbonising Transport — A Better, Greener Britain',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/610d63ffe90e0706d92fa282/decarbonising-transport-a-better-greener-britain.pdf',
  NULL,
  'Department for Transport',
  '2021-07-01', -- approximate
  ARRAY['rail','aviation','maritime','hit']::text[],
  ARRAY['decarbonisation','planning_operation','industry']::text[],
  'primary',
  'DfT cross-modal decarbonisation plan. Foundational evidence base across all transport modes. Sets economy-wide context for sector-specific strategies.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'UK Hydrogen Strategy',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/64c7e8bad8b1a70011b05e38/UK-Hydrogen-Strategy_web.pdf',
  NULL,
  'BEIS / DESNZ',
  '2021-08-01', -- approximate
  ARRAY['rail','aviation','maritime','hit']::text[],
  ARRAY['decarbonisation','industry']::text[],
  'primary',
  'Cross-economy strategy with strong transport implications across all modes. Twin-track approach: green and blue hydrogen production. 5GW by 2030 ambition (later doubled to 10GW).',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Hydrogen Strategy Update to the Market: December 2024',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/media/6761915126a2d1ff18253493/hydrogen-strategy-update-to-the-market-december-2024.pdf',
  NULL,
  'DESNZ',
  '2024-12-01', -- approximate
  ARRAY['rail','aviation','maritime','hit']::text[],
  ARRAY['decarbonisation','industry']::text[],
  'secondary',
  'Most recent market update on UK Hydrogen Strategy progress. NESO planning role, business model implementation, Track-1 cluster developments.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Future of Freight: A Long-term Plan',
  'policy_doc',
  'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1085917/future-of-freight-plan.pdf',
  NULL,
  'Department for Transport',
  '2022-06-01', -- approximate
  ARRAY['rail','aviation','maritime','hit']::text[], -- normalised order (was rail/maritime/hit/aviation)
  ARRAY['planning_operation','decarbonisation','hubs_clusters','industry']::text[],
  'primary',
  'Cross-modal freight strategy. Touches all modes. Five priorities: cost-effective, reliable, resilient; low emission; efficient and seamless; valued by society; skilled and innovative.',
  'proposed'
);

-- =========================
-- DATA & DIGITAL / CROSS-CUTTING INFRASTRUCTURE (2)
-- =========================
-- These are CPC Data & Digital architectural doctrine documents. They are
-- mode-agnostic by design (Justin Anderson's Testbed Britain framing) and
-- inform how CPC thinks about innovation infrastructure, portable assurance,
-- federation, and SME scaling — independent of specific transport modes.
--
-- The 'data_digital' value in modes is new. The Drizzle KnowledgeModeSchema
-- (see src/lib/ai/tools/kb/surface-knowledge-base.ts) currently lists only
-- {rail, aviation, maritime, hit}. A follow-up PR must extend it to include
-- data_digital, otherwise agents will filter out these documents.
--
-- Similarly, the new theme values (data_infrastructure, assurance_trust,
-- interoperability, testbeds_innovation, governance_stewardship) need to
-- be added to KnowledgeThemeSchema. Both updates land in a follow-up PR
-- after this seed has been verified in the admin UI.

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, author, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Testbed Britain: An Architecture for Scalable Innovation v1.0',
  'doctrine',
  NULL,
  'kb/testbed-britain-v1.0.pdf',
  'Connected Places Catapult',
  'Justin Anderson',
  '2026-02-13',
  ARRAY['data_digital']::text[],
  ARRAY['governance_stewardship','data_infrastructure','testbeds_innovation','assurance_trust','interoperability']::text[],
  'primary',
  'Local-file ingestion. CPC Data & Digital foundational monograph (CC BY 4.0 for architectural content). Defines four-layer pattern: stewardship between sovereign actors, governed boundaries, inspectable meaning, evidence that travels. Includes Code of Practice (Instrument I) and Architecture Requirements (Instrument II). Mode-agnostic architectural doctrine.',
  'proposed'
);

INSERT INTO atlas.knowledge_documents (
  title, source_type, source_url, storage_key,
  publisher, author, published_on,
  modes, themes, tier, summary, status
) VALUES (
  'Innovation Passports Second Level Plan v2',
  'doctrine',
  NULL,
  'kb/innovation-passports-second-level-plan-v2.docx', -- .docx extension: source format is .docx not PDF;
                                                        -- text-extractor infers format from extension via mammoth
  'Connected Places Catapult',
  'Justin Anderson',
  '2026-01-01', -- approximate
  ARRAY['data_digital']::text[],
  ARRAY['assurance_trust','testbeds_innovation','governance_stewardship']::text[],
  'primary',
  'Local-file ingestion (.docx). Operational plan for the Innovation Passport instantiation of Testbed Britain (see Annex B of monograph). Concerns portable trust and reuse of demonstrated capability across decision boundaries.',
  'proposed'
);

-- ============================================================================
-- VERIFICATION QUERIES (run manually post-apply)
-- ============================================================================
-- Expected counts (excluding the 13 pre-existing test fixture rows):
--   * 22 new rows, all status = 'proposed'
--   * Mode distribution (via unnest): rail=4+4=8 seeded, aviation=4, maritime=4, hit=4, data_digital=2
--     plus 4 cross-cutting docs contribute to rail/aviation/maritime/hit counts
--   * 3 rows with storage_key NOT NULL (RSSB, Testbed Britain, Innovation Passports)
--   * source_type CHECK now accepts 'doctrine' (2 rows)

-- 1. Total count and status distribution (exclude test fixtures)
-- SELECT status, count(*)
--   FROM atlas.knowledge_documents
--   WHERE title NOT LIKE '[KB-1 integration test]%'
--   GROUP BY status;
-- Expected: proposed: 22

-- 2. Mode distribution
-- SELECT mode, count(*)
--   FROM atlas.knowledge_documents, unnest(modes) AS mode
--   WHERE title NOT LIKE '[KB-1 integration test]%'
--   GROUP BY mode ORDER BY mode;

-- 3. Source type distribution
-- SELECT source_type, count(*)
--   FROM atlas.knowledge_documents
--   WHERE title NOT LIKE '[KB-1 integration test]%'
--   GROUP BY source_type ORDER BY source_type;
-- Expected: includes doctrine: 2

-- 4. Local-file documents (storage_key set)
-- SELECT title, storage_key
--   FROM atlas.knowledge_documents
--   WHERE storage_key IS NOT NULL
--     AND title NOT LIKE '[KB-1 integration test]%';
-- Expected: 3 rows — RSSB (.pdf), Testbed Britain (.pdf), Innovation Passports (.docx)

-- 5. Confirm CHECK constraint includes 'doctrine'
-- SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint
--   WHERE conrelid = 'atlas.knowledge_documents'::regclass
--     AND contype = 'c'
--     AND conname LIKE '%source_type%';

-- ============================================================================
-- ROLLBACK (manual, run as separate migration if needed)
-- ============================================================================
-- BEGIN;
--
-- -- 1. Delete seeded rows by title (more reliable than date-matching).
-- DELETE FROM atlas.knowledge_documents
--   WHERE title IN (
--     'Network Rail GB CP7 Delivery Plan — Year 2 update',
--     'RSSB Strategic Business Plan 2024-2029',
--     'ORR Technology Adoption in Network Rail (Targeted Assurance Review)',
--     'ORR Annual Assessment of Network Rail 2023-2024',
--     'UK Jet Zero Strategy: Delivering Net Zero Aviation by 2050',
--     'Jet Zero Strategy: One Year On',
--     'ATI Destination Zero: The Technology Journey to 2050',
--     'ATI Non-CO2 Technologies Roadmap',
--     'UK Maritime Decarbonisation Strategy',
--     'Maritime 2050: Navigating the Future',
--     'Maritime UK Annual Report 2024',
--     'UK Domestic Maritime Decarbonisation: Plotting the Course to Zero',
--     'Road Investment Strategy 3 (RIS3): 2026-2031',
--     'Automated Vehicles Act 2024',
--     'Zenzic UK CAM Roadmap to 2035 — Executive Summary',
--     'Zenzic UK CAM Roadmap 2035 — Why CAM (Opportunities)',
--     'UK Transport Decarbonisation Plan: Decarbonising Transport — A Better, Greener Britain',
--     'UK Hydrogen Strategy',
--     'Hydrogen Strategy Update to the Market: December 2024',
--     'Future of Freight: A Long-term Plan',
--     'Testbed Britain: An Architecture for Scalable Innovation v1.0',
--     'Innovation Passports Second Level Plan v2'
--   );
--
-- -- 2. Restore original CHECK constraint (without 'doctrine').
-- --    Only do this if NO doctrine-typed rows remain. Verify first:
-- --      SELECT count(*) FROM atlas.knowledge_documents WHERE source_type = 'doctrine';
-- ALTER TABLE atlas.knowledge_documents
--   DROP CONSTRAINT IF EXISTS knowledge_documents_source_type_check;
--
-- ALTER TABLE atlas.knowledge_documents
--   ADD CONSTRAINT knowledge_documents_source_type_check
--   CHECK (source_type IN (
--     'white_paper', 'policy_doc', 'govt_report', 'industry_report',
--     'guidance_doc', 'web_article', 'internal'
--   ));
--
-- COMMIT;
